database: h2
spring:
  datasource:
    hikari:
      maximum-pool-size: 24
    schema: classpath*:db/${database}/schema.sql
    data: classpath*:db/${database}/data.sql
    jpa:
      show_spl: true
      properties:
        hibernate:
          format_sql: true
    h2:
      console:
        enabled: true
spring.jpa.hibernate.ddl-auto: none
spring.datasource.initialization-mode: always
logging:
  level:
    org:
      springframework.web: debug
service.ipcheck.impl: localIpCheckServiceImpl
graphql:
  servlet:
    enabled: true
    mapping: /schema
    corsEnabled: false
    cors:
      allowed-origins: http://localhost:8080
      allowed-methods: GET, HEAD, POST, PATCH
    exception-handlers-enabled: true
    context-setting: PER_REQUEST_WITH_INSTRUMENTATION
    async-mode-enabled: true
  tools:
    schema-location-pattern: "**/*.graphqls"
    introspection-enabled: true
