CREATE TABLE author
(
    seq  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_author PRIMARY KEY (seq)
);

CREATE TABLE post
(
    seq          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id           VARCHAR(32),
    title        VARCHAR(255),
    "TEXT"       VARCHAR(255),
    category     VARCHAR(255),
    author_id    BIGINT   NULL,
    created_date datetime not null,
    CONSTRAINT pk_post PRIMARY KEY (seq)
);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES author (seq);

